# Generated by Django 4.2 on 2025-11-07 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_servermember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestats',
            old_name='total_hours',
            new_name='total_game_hours',
        ),
        migrations.RenameField(
            model_name='gamestats',
            old_name='total_sessions',
            new_name='total_game_sessions',
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='last_game',
        ),
        migrations.AddField(
            model_name='gamestats',
            name='total_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='total_voice_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to='tracker.discorduser')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('message_length', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tracker.discorduser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
