# Generated by Django 4.2 on 2025-11-08 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_total_hours_gamestats_total_game_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('game', 'Playing Game'), ('streaming', 'Streaming'), ('listening', 'Listening'), ('watching', 'Watching'), ('custom', 'Custom Status'), ('competing', 'Competing'), ('unknown', 'Unknown')], max_length=20)),
                ('activity_name', models.CharField(max_length=255)),
                ('activity_details', models.TextField(default='{}')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='tracker.discorduser')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
