# Generated by Django 4.2 on 2025-11-08 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_activityevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=255, unique=True)),
                ('instance_name', models.CharField(max_length=255)),
                ('friendly_name', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=255)),
                ('module_display_name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('running', models.BooleanField(default=False)),
                ('app_state', models.IntegerField()),
                ('cpu_usage_percent', models.FloatField(default=0)),
                ('memory_usage_mb', models.FloatField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AMPServerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage_percent', models.FloatField()),
                ('memory_usage_mb', models.FloatField()),
                ('active_users', models.IntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='tracker.ampserver')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
