# Generated by Django 4.2 on 2025-11-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_ampserver_ampservermetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampserver',
            name='module_display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
