# Generated by Django 4.2 on 2025-11-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_ampserver_module_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ampserver',
            name='cover_fetched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ampserver',
            name='cover_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
