# Generated by Django 4.2 on 2025-11-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_ampserver_cover_fetched_ampserver_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ampserver',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
