# Generated by Django 4.2 on 2025-11-09 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_ampserver_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=255, unique=True)),
                ('total_seconds', models.BigIntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gaming_seconds', models.BigIntegerField(default=0)),
                ('total_voice_seconds', models.BigIntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='user',
        ),
        migrations.DeleteModel(
            name='ServerMember',
        ),
        migrations.AlterModelOptions(
            name='discorduser',
            options={},
        ),
        migrations.RemoveField(
            model_name='activityevent',
            name='duration_seconds',
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='activity_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='activity_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='started_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.discorduser'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='started_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.discorduser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.discorduser'),
        ),
        migrations.AlterField(
            model_name='voicesession',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voicesession',
            name='started_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='voicesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.discorduser'),
        ),
        migrations.DeleteModel(
            name='GameStats',
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='tracker.discorduser'),
        ),
    ]
