# Generated by Django 4.2 on 2025-11-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_gamestatistic_userstatistic_remove_gamestats_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatistic',
            name='total_seconds_this_month',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestatistic',
            name='total_seconds_this_week',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='total_gaming_seconds_this_month',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='total_gaming_seconds_this_week',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='total_messages_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='total_messages_this_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='total_voice_seconds_this_month',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='total_voice_seconds_this_week',
            field=models.BigIntegerField(default=0),
        ),
    ]
