# Generated by Django 4.2 on 2026-04-10 02:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_gamestatistic_total_seconds_this_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyGameStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=255, unique=True)),
                ('week_start', models.DateField(default=datetime.date.today)),
                ('seconds', models.BigIntegerField(default=0)),
                ('sessions', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyUserStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(default=datetime.date.today)),
                ('gaming_seconds', models.BigIntegerField(default=0)),
                ('sessions', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_statistic', to='tracker.discorduser')),
            ],
        ),
    ]
