# Generated by Django 4.2 on 2026-04-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_weeklygamestatistic_weeklyuserstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatistic',
            name='steam_app_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
