# Generated by Django 4.2 on 2026-04-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_gamestatistic_steam_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ampserver',
            name='steam_app_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
